---
name: test-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUAdhiB4hX2tS6Pl5zyV7h9hpqyUEwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yNjAzMDUxNzQ0MDBaFw00MTAzMDExNzQ0MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARiOyLy17CaBq8R
          gMOiAMB7SwEtmGLbtjxEWV/lYq1MwzEl+GoVU1AVFa2cswBBeGVHhYrf2wYxdlxj
          75N32p+ho0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQU7kcLp/oW52U0yQpT7+yyc38NGecwCgYIKoZIzj0EAwIDRwAwRAIg
          D0bQ5Gw1G9ZikzB+0g1UkdAhKvCsM6QbsGvQJOdZk+ACIDHMeW8fic1/RoGBqE46
          IFgX30WeFXh0BrGDOBLX9y1i
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICHjCCAcWgAwIBAgIUAdhiB4hX2tS6Pl5zyV7h9hpqyUEwCgYIKoZIzj0EAwIw
          bDELMAkGA1UEBhMCVUsxEjAQBgNVBAgTCUhhbXBzaGlyZTEQMA4GA1UEBxMHSHVy
          c2xleTEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eub3Jn
          Mi5leGFtcGxlLmNvbTAeFw0yNjAzMDUxNzQ0MDBaFw00MTAzMDExNzQ0MDBaMGwx
          CzAJBgNVBAYTAlVLMRIwEAYDVQQIEwlIYW1wc2hpcmUxEDAOBgNVBAcTB0h1cnNs
          ZXkxGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2NhLm9yZzIu
          ZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARiOyLy17CaBq8R
          gMOiAMB7SwEtmGLbtjxEWV/lYq1MwzEl+GoVU1AVFa2cswBBeGVHhYrf2wYxdlxj
          75N32p+ho0UwQzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAd
          BgNVHQ4EFgQU7kcLp/oW52U0yQpT7+yyc38NGecwCgYIKoZIzj0EAwIDRwAwRAIg
          D0bQ5Gw1G9ZikzB+0g1UkdAhKvCsM6QbsGvQJOdZk+ACIDHMeW8fic1/RoGBqE46
          IFgX30WeFXh0BrGDOBLX9y1i
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
