---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICVzCCAf6gAwIBAgIRAKHgQLl5QfQEcwZP+5hiw+gwCgYIKoZIzj0EAwIwdjEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
          c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjYwMzA0MDQxMjAwWhcNMzYwMzAxMDQx
          MjAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
          BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G
          A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
          AwEHA0IABFgrct40jut4wxM8Bx4zWg2RSVvFGbSgSmvT7o2KzNmZlfOWinqZ5eg1
          eC72RErzROGYZM7Whrh7d0PjZCZTg8WjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
          HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
          HQ4EIgQglAb8O31dFcR3Kz2jteBBV+OTXD3ExeFBXU0vvLAtNdQwCgYIKoZIzj0E
          AwIDRwAwRAIgF3H4bqhbUkBwtK7+/z3dpOP9fZpulB7UycnaddqVsQACIFTNqhgc
          bvPm3vdd0pEgUUE+DgfR+GtrrRO4Br1kNwoQ
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICUjCCAfigAwIBAgIRAJbcjfsljAfkR6DXpFLeUDQwCgYIKoZIzj0EAwIwczEL
          MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
          cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
          Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjYwMzA0MDQxMjAwWhcNMzYwMzAxMDQxMjAw
          WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
          U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
          AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
          BAQl+KgE7tJWrMyPbXyqedAfffnNm/VSHHnd2ml7kuUW8HH648wa8nr2wSko2wRE
          5jm2lq1v457xI+ZaQpEweU+jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAU
          BggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg
          uLojEQISeb1mpigeMxrv7RURX3EzcBACg2GW5F3NNUowCgYIKoZIzj0EAwIDSAAw
          RQIgZeFNspJrC0lWGypq2D6Z64JnCKaSaKBm+BphgSAVCngCIQCedDLpxJ7XaUHk
          X691ki9ZJzF7Q7dfcVbCzHNxsAyJ2Q==
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
